name: Pipeline CI Selenium

on:
  push:
    branches:
      - main
      - master

jobs:

  selenium-test:

    runs-on: ubuntu-latest

    steps:

    - name: Baixar projeto
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install selenium webdriver-manager

    - name: Instalar Google Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Executar testes Selenium
      run: |
        python tests/selenium/test_site.py